# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

proc load_customLib_library { dir basename } {
    if { $::tcl_platform(pointerSize) == 8 } {
	set bits 64
    } else {
	set bits 32
    }
    set library ${basename}_${bits}[info sharedlibextension]
    load [file normalize [file join $dir $library]] $basename    
}

package ifneeded customLib_utils::c 1.22.3 [list load_customLib_library \
	$dir customLib_utils]

set cmd ""
lappend cmd [list package require customLib_utils::tk]
lappend cmd [list load_customLib_library $dir customLib_utils_tk]

package ifneeded customLib_utils::img 1.22.3 [join $cmd ";"]
