# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded gid_helpviewer 1.1 [list source [file join $dir gid_helpviewer.tcl]]

package ifneeded helpviewer 1.4 [list source [file join $dir helpviewer_back_compatibility.tcl]]